[tools]
biome = "latest"
bun = "latest"

[tasks.format]
run = "biome format . --write"
description = "Format source files with Biome"

[tasks.build]
run = "tsc"
description = "Build TypeScript files for publishing"
